In [1]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

vector1 = arr = np.zeros(9)
vector2 = arr = np.zeros(9)

vector1[:5]  = 1
vector2[:5] = 1

np.random.shuffle(vector1)
np.random.shuffle(vector2)

print(vector1)
print(vector2)
score = cosine_similarity([vector1], [vector2])
score

[0. 1. 1. 0. 1. 1. 1. 0. 0.]
[0. 0. 1. 1. 1. 0. 0. 1. 1.]


array([[0.4]])

In [2]:
data_set = ["Cops shoot fire", "Cops face the bad guys"]

vectorizer = CountVectorizer(stop_words="english")
sparse_matrix = vectorizer.fit_transform(data_set)

print(vectorizer.get_feature_names())
print(sparse_matrix)
print(sparse_matrix.todense())

['bad', 'cops', 'face', 'guys', 'shoot']
  (0, 1)	1
  (0, 4)	1
  (1, 1)	1
  (1, 2)	1
  (1, 0)	1
  (1, 3)	1
[[0 1 0 0 1]
 [1 1 1 1 0]]


In [5]:
tfidf_transform = TfidfTransformer()
tfidf_transform.fit(sparse_matrix)
print("IDF: ", tfidf_transform.idf_)

IDF:  [1.40546511 1.         1.40546511 1.40546511 1.40546511]


In [4]:
import numpy as np
import pandas as pd

np.random.seed(234)
aleatorios = np.random.randint(low = 950, high = 1050, size=100)
df = pd.DataFrame(aleatorios, columns=["preco"])
df

preco
0    1022
1     981
2    1018
3    1007
4    1045
..    ...
95    961
96    951
97   1031
98    992
99    955

[100 rows x 1 columns]

In [9]:
df['crescimento'] = df.preco.shift(-1).div(df.preco) - 1
df.head()

preco  crescimento
0   1022    -0.040117
1    981     0.037717
2   1018    -0.010806
3   1007     0.037736
4   1045    -0.059330

In [11]:
df['crescimento_direto'] = df.preco.pct_change()
df.head()

preco  crescimento  crescimento_direto
0   1022    -0.040117                 NaN
1    981     0.037717           -0.040117
2   1018    -0.010806            0.037717
3   1007     0.037736           -0.010806
4   1045    -0.059330            0.037736